apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: weather-proxy
  description: A weather proxy service for fetching weather data.
spec:
  targets:
    - ./backstage/databases.yaml
    - ./backstage/weather-api.yaml
    - ./backstage/components.yaml
